# Generated by Django 3.0 on 2019-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia_Agentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_mobilidade', models.CharField(max_length=40)),
                ('situacao', models.CharField(blank=True, choices=[('PRESENTE', 'PRESENTE'), ('EXTRA', 'EXTRA'), ('FALTA', 'FALTA'), ('FALTA JUSTIFICADA', 'FALTA JUSTIFICADA'), ('FOLGA', 'FOLGA'), ('FERIAS', 'FERIAS'), ('LICENÇA', 'LICENÇA'), ('PERMUTA', 'PERMUTA')], default='PRESENTE', max_length=50, null=True)),
                ('data', models.DateField()),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('total_hora', models.TimeField()),
            ],
        ),
    ]
