# Generated by Django 3.0 on 2019-12-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fqc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia_agentes',
            name='total_hora',
        ),
    ]
