# Generated by Django 3.0 on 2019-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fqc', '0002_remove_frequencia_agentes_total_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia_agentes',
            name='total_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
