# Generated by Django 3.0 on 2020-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fqc', '0003_frequencia_agentes_total_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia_agentes',
            name='horario_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='frequencia_agentes',
            name='horario_saida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='frequencia_agentes',
            name='total_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
